[package]
name = "hft"
version = "0.1.0"
authors = ["Maxim Vorobjov <maxim.vorobjov@gmail.com>"]
edition = "2018"

[dependencies]
slotmap = "1.0"
nanorand = { version = "0.5", features = ["wyrand"] }
merging-iterator = "1.3.0"
rayon = "1.5.0"
statistical = "1.0"
